language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
    - os: osx

script:
  - ./waf configure build
  - ./waf configure build install --test_build
  - ./test_driver.py

addons:
  apt:
    packages:
    - libarchive-dev
    - libjudy-dev
    - pkg-config

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install judy libarchive; fi
