language: c

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python judy libarchive; fi

addons:
  apt:
    packages:
    - libarchive-dev
    - libjudy-dev
    - pkg-config

script:
  - ./waf configure build
  - ./waf configure build --test_build
  - sudo ./waf install
  - python ./test_driver.py

